src/Entity/AudioUpload.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AudioUploadRepository")
 */
class AudioUpload
{
    const UPLOAD_STATUS_CHUNKED = 0;
    const UPLOAD_STATUS_UPLOADED = 1;
    const UPLOAD_STATUS_TRANSCRIBED = 2;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"rest"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank()
     * @Groups({"rest"})
     */
    private $filename;

    /**
     * @ORM\Column(type="datetime")
     * @Groups({"rest"})
     */
    private $uploadDate;

    /**
     * 0: Chunked
     * 1: Uploaded
     * 2: Transcribed
     *
     * @ORM\Column(type="integer")
     * @Assert\Choice({0, 1, 2})
     * @Groups({"rest"})
     */
    private $status;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isDeleted = false;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\AudioUploadChunk", mappedBy="audioUpload", orphanRemoval=true)
     */
    private $audioUploadChunks;

    /**
     * @Groups({"rest"})
     *
     * @var string
     */
    private $audioUrl;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"rest"})
     *
     * @var string
     */
    private $transcriptionFilename;

    /**
     * @Groups({"rest"})
     *
     * @var string
     */
    private $transcriptionUrl;

    /**
     * @return string
     */
    public function getTranscriptionUrl(): ?string
    {
        return $this->transcriptionUrl;
    }

    /**
     * @param string $transcriptionUrl
     */
    public function setTranscriptionUrl(string $transcriptionUrl): void
    {
        $this->transcriptionUrl = $transcriptionUrl;
    }

    /**
     * @return string
     */
    public function getTranscriptionFilename(): ?string
    {
        return $this->transcriptionFilename;
    }

    /**
     * @param string $transcriptionFilename
     */
    public function setTranscriptionFilename(string $transcriptionFilename): void
    {
        $this->transcriptionFilename = $transcriptionFilename;
    }

    /**
     * @return string
     */
    public function getAudioUrl(): string
    {
        return $this->audioUrl;
    }

    /**
     * @param string $audioUrl
     */
    public function setAudioUrl(string $audioUrl): void
    {
        $this->audioUrl = $audioUrl;
    }

    public function __construct()
    {
        $this->audioUploadChunks = new ArrayCollection();
        $this->setIsDeleted(false);
        $this->setStatus(self::UPLOAD_STATUS_CHUNKED);
        $this->setUploadDate(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUploadDate(): ?\DateTimeInterface
    {
        return $this->uploadDate;
    }

    public function setUploadDate(\DateTimeInterface $uploadDate): self
    {
        $this->uploadDate = $uploadDate;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * @Groups({"rest"})
     *
     * @return string
     */
    public function getStatusName(): string
    {
        return [
            'UPLOADING',
            'TRANSCRIBING',
            'COMPLETE',
        ][$this->status];
    }

    public function setStatus(int $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    /**
     * @return Collection|AudioUploadChunk[]
     */
    public function getAudioUploadChunks(): Collection
    {
        return $this->audioUploadChunks;
    }

    public function addAudioUploadChunk(AudioUploadChunk $audioUploadChunk): self
    {
        if (!$this->audioUploadChunks->contains($audioUploadChunk)) {
            $this->audioUploadChunks[] = $audioUploadChunk;
            $audioUploadChunk->setAudioUpload($this);
        }

        return $this;
    }

    public function removeAudioUploadChunk(AudioUploadChunk $audioUploadChunk): self
    {
        if ($this->audioUploadChunks->contains($audioUploadChunk)) {
            $this->audioUploadChunks->removeElement($audioUploadChunk);
            // set the owning side to null (unless already changed)
            if ($audioUploadChunk->getAudioUpload() === $this) {
                $audioUploadChunk->setAudioUpload(null);
            }
        }

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;


use App\Repository\AudioUploadRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class MainController extends AbstractController
{
    /**
     * @Route("/")
     *
     * @param Request $request
     * @return Response
     */
    public function show(Request $request, AudioUploadRepository $audioUploadRepository)
    {
        return $this->render('main/show.html.twig', [
            'audioUploads' => $audioUploadRepository->findBy(
                ['isDeleted' => 0],
                ['uploadDate' => 'desc']
            )
        ]);
    }
}

templates/main/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <section class="container mt-3">
        <div class="panel-heading">
            <div class="row">
                <div class="col col-xs-6">
                    <h3 class="panel-title">Text2Speech API</h3>
                </div>
                <div class="col col-xs-6 text-right">
                    <button style="display: none;" class="btn btn-sm btn-success js-file-processing" disabled>Processing...</button>
                    <button class="btn btn-sm btn-success js-file-upload">Upload</button>
                    <input class="js-file-select" type="file" id="file-input" style="display:none;">
                    <button class="btn btn-sm btn-danger js-delete-audio">Delete</button>
                </div>
            </div>
        </div>

        <table id="mytable" class="table table-bordred table-striped">
            <thead>
                <th><input type="checkbox" class="js-audio-header-check"></th>
                <th width="30%">Filename</th>
                <th>Upload Date</th>
                <th>Status</th>
                <th width="25%">Actions</th>
            </thead>
            <tbody class="js-upload-list">
                {% for audioUpload in audioUploads %}
                    <tr class="js-row-{{ audioUpload.id }}">
                        <td><input class="js-audio-row-check" type="checkbox" value="{{ audioUpload.id }}"></td>
                        <td>{{ audioUpload.filename }}</td>
                        <td>{{ audioUpload.uploadDate|date('Y-m-d H:i:s')  }}</td>
                        <td>{{ audioUpload.statusName }}</td>
                        <td>
                            {% if audioUpload.status > 0 %}
                                <audio controls>
                                    <source src="{{ audioUpload.audioUrl }}" type="audio/wav">
                                </audio>
                            {% endif %}
                            {% if audioUpload.status > 1 %}
                                <a class="btn btn-link" href="{{ audioUpload.transcriptionUrl }}" target="_blank">Transcription</a>
                            {% endif %}
                        </td>
                    </tr>
                {% else %}
                    <tr class="js-no-row">
                        <td></td>
                        <td>No audio uploads yet</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="bundles/goswebsocket/js/gos_web_socket_client.js"></script>
    <script src="bundles/goswebsocket/js/vendor/autobahn.min.js"></script>
    <script type="text/javascript">
        var _WS_URI = "ws://{{ gos_web_socket_server_host }}";
    </script>
    <script src="{{ asset('js/main.js') }}"></script>
{% endblock %}